// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBqvL5zVd5xHgDSeaGDa8BTkUTprb_uFTI',
    appId: '1:96398064218:web:1dd23951b7f4ab57e6b663',
    messagingSenderId: '96398064218',
    projectId: 'amomeal',
    authDomain: 'amomeal.firebaseapp.com',
    storageBucket: 'amomeal.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCMLHy_ZIOczwwgSsqK4PXDN4IVj4vlqHM',
    appId: '1:96398064218:android:966426f628ecbdc2e6b663',
    messagingSenderId: '96398064218',
    projectId: 'amomeal',
    storageBucket: 'amomeal.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDqhLtQZqCSkTa82pi4Wh-KCH5Sxu7xfJk',
    appId: '1:96398064218:ios:253631191934d11ae6b663',
    messagingSenderId: '96398064218',
    projectId: 'amomeal',
    storageBucket: 'amomeal.firebasestorage.app',
    iosBundleId: 'com.example.testing',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDqhLtQZqCSkTa82pi4Wh-KCH5Sxu7xfJk',
    appId: '1:96398064218:ios:253631191934d11ae6b663',
    messagingSenderId: '96398064218',
    projectId: 'amomeal',
    storageBucket: 'amomeal.firebasestorage.app',
    iosBundleId: 'com.example.testing',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBqvL5zVd5xHgDSeaGDa8BTkUTprb_uFTI',
    appId: '1:96398064218:web:e48f07c09020cf7fe6b663',
    messagingSenderId: '96398064218',
    projectId: 'amomeal',
    authDomain: 'amomeal.firebaseapp.com',
    storageBucket: 'amomeal.firebasestorage.app',
  );
}
