package com.amomeal.marketplace.common.util;

import java.math.BigDecimal;
import java.math.RoundingMode;
import java.time.Duration;
import java.time.Instant;
import java.time.OffsetDateTime;
import java.time.ZoneOffset;
import java.time.format.DateTimeFormatter;
import java.util.List;

/**
 * Python-compatible numeric helpers, shared across modules that need to reproduce Django's exact
 * arithmetic. Originally lived in {@code recommendation.service} (pinned against the real Django
 * code there — see {@code PythonParityTest} + the JSON fixture generated by
 * {@code src/test/resources/recommendation/gen_vectors.py} in backend/venv); moved here so
 * {@code dish}'s {@code DishNutritionService.pyRound} can reuse the same exact {@link #round}
 * instead of its own divergent implementation.
 *
 * <p><b>Why {@link #round} and not {@code BigDecimal.valueOf(x).setScale(...)}?</b>
 * {@code BigDecimal.valueOf(x)} rounds the <i>shortest decimal string</i> of the double — not the
 * <i>exact binary value</i> Python's {@code round(x, n)} rounds. They disagree on binary
 * "near-ties": {@code round(2.675, 2)} is 2.67 in Python (2.675 is stored as 2.67499999...), the
 * shortest-string approach gives 2.68; {@code round(0.0005, 3)} is 0.001 in Python, the
 * shortest-string approach gives 0.0. Verified in backend/venv (fixture key {@code pyround}).
 */
public final class PyMath {

    private static final DateTimeFormatter ISO_SECONDS = DateTimeFormatter.ofPattern("yyyy-MM-dd'T'HH:mm:ss");

    private PyMath() {
    }

    /** Exactly Python's {@code round(value, digits)} for floats (exact binary value, half-even, sign kept). */
    public static double round(double value, int digits) {
        if (Double.isNaN(value) || Double.isInfinite(value)) {
            return value;
        }
        double rounded = new BigDecimal(value).setScale(digits, RoundingMode.HALF_EVEN).doubleValue();
        if (rounded == 0.0 && (value < 0 || (value == 0.0 && 1.0 / value < 0))) {
            return -0.0;
        }
        return rounded;
    }

    /** Python {@code max(lower, min(value, upper))} with the default [0, 1] clamp. */
    public static double clamp(double value) {
        return clamp(value, 0.0, 1.0);
    }

    /**
     * Python {@code max(lower, min(value, upper))}. Python's builtin min/max keep the first
     * argument unless a later one compares strictly smaller/greater, so NaN handling differs from
     * {@link Math#max}; reproduced literally.
     */
    public static double clamp(double value, double lower, double upper) {
        return pyMax(lower, pyMin(value, upper));
    }

    /** Python {@code max(a, b)}: returns {@code a} unless {@code b > a}. */
    public static double pyMax(double a, double b) {
        return b > a ? b : a;
    }

    /** Python {@code min(a, b)}: returns {@code a} unless {@code b < a}. */
    public static double pyMin(double a, double b) {
        return b < a ? b : a;
    }

    /** Python {@code max(iterable)} over a non-empty list (first element wins ties / NaN). */
    public static double pyMax(List<Double> values) {
        double best = values.get(0);
        for (int i = 1; i < values.size(); i++) {
            double v = values.get(i);
            if (v > best) {
                best = v;
            }
        }
        return best;
    }

    /**
     * {@code max((now - created_at).total_seconds(), 0) / 86400} with timedelta's microsecond
     * resolution ({@code total_seconds()} is exact micros / 10**6).
     */
    public static double ageDays(Instant now, Instant createdAt) {
        return Math.max(totalSeconds(now, createdAt), 0.0) / 86400;
    }

    /** {@code (now - then).total_seconds()} at microsecond resolution. */
    public static double totalSeconds(Instant now, Instant then) {
        long micros = Math.floorDiv(Duration.between(then, now).toNanos(), 1000L);
        return micros / 1_000_000.0;
    }

    /** Python {@code str(float)}-equivalent enough for pgvector literals ({@code [a,b,c]}). */
    public static String vectorLiteral(List<Double> vector) {
        StringBuilder sb = new StringBuilder("[");
        for (int i = 0; i < vector.size(); i++) {
            if (i > 0) {
                sb.append(',');
            }
            sb.append(Double.toString(vector.get(i)));
        }
        return sb.append(']').toString();
    }

    /** Python {@code datetime.isoformat()} of an aware UTC datetime ({@code +00:00}, micros only when non-zero). */
    public static String isoformat(Instant instant) {
        OffsetDateTime odt = instant.atOffset(ZoneOffset.UTC);
        int micros = odt.getNano() / 1000;
        String base = odt.format(ISO_SECONDS);
        if (micros != 0) {
            base = base + "." + String.format("%06d", micros);
        }
        return base + "+00:00";
    }
}
